version: "3"

services:
  # Application
  backend:
    hostname: backend
    container_name: backend
    build:
      context: .
      dockerfile: DockerFile
    ports:
    - "8080:8080"
    volumes:
    - ./app:/app
    - ./secrets:/secrets
    - ./www/media:/www/media
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver_plus 0.0.0.0:8080 --cert-file cert.crt"
    environment:
      - SECRETS_PATH_FILE=/secrets/.env

